# Generated by Django 5.2.17 on 2026-09-01 10:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='client_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_information', models.JSONField(default=dict)),
                ('reputation', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'client_profiles',
                'constraints': [models.CheckConstraint(condition=models.Q(('reputation__gte', 0), ('reputation__lte', 5)), name='client_reputation_between_zero_and_five')],
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('admin_handling', models.TextField(blank=True, default='')),
                ('resolution', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raised_by', models.ForeignKey(db_column='raised_by', on_delete=django.db.models.deletion.RESTRICT, related_name='raised_disputes', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, db_column='reviewed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'disputes',
            },
        ),
        migrations.CreateModel(
            name='DisputeParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispute', models.ForeignKey(db_column='dispute_id', on_delete=django.db.models.deletion.RESTRICT, to='clients.dispute')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dispute_users',
            },
        ),
        migrations.AddField(
            model_name='dispute',
            name='involved_users',
            field=models.ManyToManyField(related_name='disputes', through='clients.DisputeParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('required_skills', models.JSONField(default=list)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('reference_files', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('POSTED', 'Posted'), ('APPLICATIONS', 'Applications'), ('STUDENT_SELECTED', 'Student Selected'), ('IN_PROGRESS', 'In Progress'), ('WORK_SUBMITTED', 'Work Submitted'), ('PAYMENT', 'Payment'), ('COMPLETED', 'Completed'), ('RATED', 'Rated')], db_column='job_state', default='POSTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_provider', models.ForeignKey(db_column='job_provider', on_delete=django.db.models.deletion.RESTRICT, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
                ('selected_student', models.ForeignKey(blank=True, db_column='selected_student', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.AddField(
            model_name='dispute',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='disputes', to='clients.job'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_information', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('SELECTED', 'Selected')], db_column='application_status', default='APPLIED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_message', models.TextField(blank=True, default='')),
                ('expected_completion', models.DateField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='clients.job')),
            ],
            options={
                'db_table': 'applications',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='clients.job')),
                ('sender', models.ForeignKey(db_column='sender', on_delete=django.db.models.deletion.RESTRICT, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('platform_commission', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transaction_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_column='transaction_state', default='PENDING', max_length=10)),
                ('transaction_reference', models.TextField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='clients.job')),
                ('payer', models.ForeignKey(db_column='payer', on_delete=django.db.models.deletion.RESTRICT, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(db_column='recipient', on_delete=django.db.models.deletion.RESTRICT, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.SmallIntegerField()),
                ('review_content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='clients.job')),
                ('reviewed_user', models.ForeignKey(db_column='reviewed_user', on_delete=django.db.models.deletion.RESTRICT, related_name='received_ratings', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(db_column='reviewer', on_delete=django.db.models.deletion.RESTRICT, related_name='given_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ratings',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=20)),
                ('admin_action', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_job', models.ForeignKey(blank=True, db_column='related_job', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='related_reports', to='clients.job')),
                ('reported_job', models.ForeignKey(blank=True, db_column='reported_job', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='reports', to='clients.job')),
                ('reported_user', models.ForeignKey(blank=True, db_column='reported_user', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(db_column='reporter', on_delete=django.db.models.deletion.RESTRICT, related_name='reports_filed', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, db_column='reviewed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_work', models.JSONField(default=list)),
                ('submission_information', models.JSONField(default=dict)),
                ('submission_status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='clients.job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='work_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submissions',
            },
        ),
        migrations.AddConstraint(
            model_name='disputeparticipant',
            constraint=models.UniqueConstraint(fields=('dispute', 'user'), name='unique_dispute_participant'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_provider'], name='jobs_provider_idx'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('budget__gte', 0)), name='job_budget_non_negative'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['status'], name='disputes_status_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['student'], name='applications_student_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('job', 'student'), name='one_application_per_student_per_job'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'SELECTED')), fields=('job',), name='one_selected_application_per_job'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['job'], name='messages_job_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('message', ''), _negated=True), name='message_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='payment_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('platform_commission__gte', 0), ('platform_commission__lte', models.F('amount'))), name='payment_commission_in_range'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('payer', models.F('recipient')), _negated=True), name='payment_payer_not_recipient'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='rating_between_one_and_five'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.CheckConstraint(condition=models.Q(('reviewer', models.F('reviewed_user')), _negated=True), name='rating_reviewer_not_reviewed'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('job', 'reviewer', 'reviewed_user'), name='one_rating_per_reviewer_per_job'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='reports_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(('reported_user__isnull', False), ('reported_job__isnull', False), ('related_job__isnull', False), _connector='OR'), name='report_requires_target'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['job'], name='submissions_job_idx'),
        ),
    ]
