# Generated by Django 5.2.17 on 2026-08-28 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_authtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthToken',
        ),
    ]
