from django.conf import settings
from django.db import migrations, models
from django.db.models import F, Q
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("students", "0002_canonical_profile_and_verification_contract"),
        ("clients", "0001_initial"),
        ("accounts", "0005_canonical_user_contract"),
    ]

    operations = [
        migrations.RenameModel(old_name="JobApplication", new_name="Application"),
        migrations.RenameModel(old_name="Communication", new_name="Message"),
        migrations.RenameModel(old_name="WorkSubmission", new_name="Submission"),
        migrations.RenameModel(old_name="Reporting", new_name="Report"),
        migrations.AlterModelTable(name="clientprofile", table="client_profiles"),
        migrations.AlterModelTable(name="job", table="jobs"),
        migrations.AlterModelTable(name="application", table="applications"),
        migrations.AlterModelTable(name="message", table="messages"),
        migrations.AlterModelTable(name="submission", table="submissions"),
        migrations.AlterModelTable(name="payment", table="payments"),
        migrations.AlterModelTable(name="rating", table="ratings"),
        migrations.AlterModelTable(name="report", table="reports"),
        migrations.AlterModelTable(name="dispute", table="disputes"),
        migrations.RemoveField(model_name="clientprofile", name="id"),
        migrations.AlterField(model_name="clientprofile", name="user", field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name="client_profile", serialize=False, to=settings.AUTH_USER_MODEL)),
        migrations.AlterField(model_name="clientprofile", name="profile_information", field=models.JSONField(default=dict)),
        migrations.AddField(model_name="clientprofile", name="reputation", field=models.DecimalField(decimal_places=2, default=0, max_digits=3)),
        migrations.AddConstraint(model_name="clientprofile", constraint=models.CheckConstraint(condition=Q(reputation__gte=0) & Q(reputation__lte=5), name="client_reputation_between_zero_and_five")),
        migrations.RenameField(model_name="job", old_name="provider", new_name="job_provider"),
        migrations.AlterField(model_name="job", name="job_provider", field=models.ForeignKey(db_column="job_provider", on_delete=django.db.models.deletion.RESTRICT, related_name="posted_jobs", to=settings.AUTH_USER_MODEL)),
        migrations.RemoveField(model_name="job", name="required_skills"),
        migrations.AddField(model_name="job", name="required_skills", field=models.JSONField(default=list)),
        migrations.AlterField(model_name="job", name="reference_files", field=models.JSONField(default=list)),
        migrations.AlterField(model_name="job", name="deadline", field=models.DateTimeField(blank=True, null=True)),
        migrations.AlterField(model_name="job", name="budget", field=models.DecimalField(decimal_places=2, max_digits=12)),
        migrations.AlterField(model_name="job", name="status", field=models.CharField(choices=[("POSTED", "Posted"), ("APPLICATIONS", "Applications"), ("STUDENT_SELECTED", "Student Selected"), ("IN_PROGRESS", "In Progress"), ("WORK_SUBMITTED", "Work Submitted"), ("PAYMENT", "Payment"), ("COMPLETED", "Completed"), ("RATED", "Rated")], db_column="job_state", default="POSTED", max_length=20)),
        migrations.AlterField(model_name="job", name="selected_student", field=models.ForeignKey(blank=True, db_column="selected_student", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_jobs", to=settings.AUTH_USER_MODEL)),
        migrations.AddConstraint(model_name="job", constraint=models.CheckConstraint(condition=Q(budget__gte=0), name="job_budget_non_negative")),
        migrations.AddIndex(model_name="job", index=models.Index(fields=["job_provider"], name="jobs_provider_idx")),
        migrations.AddField(model_name="application", name="application_information", field=models.JSONField(default=dict)),
        migrations.AddField(model_name="application", name="updated_at", field=models.DateTimeField(auto_now=True, null=True)),
        migrations.AlterField(model_name="application", name="student", field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name="job_applications", to=settings.AUTH_USER_MODEL)),
        migrations.AlterField(model_name="application", name="status", field=models.CharField(choices=[("APPLIED", "Applied"), ("SELECTED", "Selected")], db_column="application_status", default="APPLIED", max_length=10)),
        migrations.AlterField(model_name="application", name="application_message", field=models.TextField(blank=True, default="")),
        migrations.AlterField(model_name="application", name="expected_completion", field=models.DateField(blank=True, null=True)),
        migrations.AddConstraint(model_name="application", constraint=models.UniqueConstraint(fields=("job", "student"), name="one_application_per_student_per_job")),
        migrations.AddConstraint(model_name="application", constraint=models.UniqueConstraint(condition=Q(status="SELECTED"), fields=("job",), name="one_selected_application_per_job")),
        migrations.AddIndex(model_name="application", index=models.Index(fields=["student"], name="applications_student_idx")),
        migrations.AlterField(model_name="message", name="sender", field=models.ForeignKey(db_column="sender", on_delete=django.db.models.deletion.RESTRICT, related_name="sent_messages", to=settings.AUTH_USER_MODEL)),
        migrations.AddConstraint(model_name="message", constraint=models.CheckConstraint(condition=~Q(message=""), name="message_not_empty")),
        migrations.AddIndex(model_name="message", index=models.Index(fields=["job"], name="messages_job_idx")),
        migrations.AlterField(model_name="submission", name="student", field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name="work_submissions", to=settings.AUTH_USER_MODEL)),
        migrations.AlterField(model_name="submission", name="submitted_work", field=models.JSONField(default=list)),
        migrations.AlterField(model_name="submission", name="submission_information", field=models.JSONField(default=dict)),
        migrations.AlterField(model_name="submission", name="submission_status", field=models.CharField(choices=[("SUBMITTED", "Submitted"), ("ACCEPTED", "Accepted"), ("REJECTED", "Rejected")], default="SUBMITTED", max_length=10)),
        migrations.AddField(model_name="submission", name="created_at", field=models.DateTimeField(auto_now_add=True, null=True)),
        migrations.AddField(model_name="submission", name="updated_at", field=models.DateTimeField(auto_now=True, null=True)),
        migrations.AddIndex(model_name="submission", index=models.Index(fields=["job"], name="submissions_job_idx")),
        migrations.AlterField(model_name="payment", name="job", field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name="payments", to="clients.job")),
        migrations.AlterField(model_name="payment", name="payer", field=models.ForeignKey(db_column="payer", on_delete=django.db.models.deletion.RESTRICT, related_name="payments_made", to=settings.AUTH_USER_MODEL)),
        migrations.AlterField(model_name="payment", name="recipient", field=models.ForeignKey(db_column="recipient", on_delete=django.db.models.deletion.RESTRICT, related_name="payments_received", to=settings.AUTH_USER_MODEL)),
        migrations.AlterField(model_name="payment", name="amount", field=models.DecimalField(decimal_places=2, max_digits=12)),
        migrations.AlterField(model_name="payment", name="platform_commission", field=models.DecimalField(decimal_places=2, default=0, max_digits=12)),
        migrations.AlterField(model_name="payment", name="transaction_status", field=models.CharField(choices=[("PENDING", "Pending"), ("COMPLETED", "Completed"), ("FAILED", "Failed"), ("REFUNDED", "Refunded")], db_column="transaction_state", default="PENDING", max_length=10)),
        migrations.AddField(model_name="payment", name="transaction_reference", field=models.TextField(blank=True, null=True, unique=True)),
        migrations.AddField(model_name="payment", name="created_at", field=models.DateTimeField(auto_now_add=True, null=True)),
        migrations.AddField(model_name="payment", name="updated_at", field=models.DateTimeField(auto_now=True, null=True)),
        migrations.AddConstraint(model_name="payment", constraint=models.CheckConstraint(condition=Q(amount__gte=0), name="payment_amount_non_negative")),
        migrations.AddConstraint(model_name="payment", constraint=models.CheckConstraint(condition=Q(platform_commission__gte=0) & Q(platform_commission__lte=F("amount")), name="payment_commission_in_range")),
        migrations.AddConstraint(model_name="payment", constraint=models.CheckConstraint(condition=~Q(payer=F("recipient")), name="payment_payer_not_recipient")),
        migrations.AlterField(model_name="rating", name="reviewer", field=models.ForeignKey(db_column="reviewer", on_delete=django.db.models.deletion.RESTRICT, related_name="given_ratings", to=settings.AUTH_USER_MODEL)),
        migrations.AlterField(model_name="rating", name="reviewed_user", field=models.ForeignKey(db_column="reviewed_user", on_delete=django.db.models.deletion.RESTRICT, related_name="received_ratings", to=settings.AUTH_USER_MODEL)),
        migrations.AlterField(model_name="rating", name="rating", field=models.SmallIntegerField()),
        migrations.AlterField(model_name="rating", name="review_content", field=models.TextField(blank=True, default="")),
        migrations.AddField(model_name="rating", name="created_at", field=models.DateTimeField(auto_now_add=True, null=True)),
        migrations.AddField(model_name="rating", name="updated_at", field=models.DateTimeField(auto_now=True, null=True)),
        migrations.AddConstraint(model_name="rating", constraint=models.CheckConstraint(condition=Q(rating__gte=1) & Q(rating__lte=5), name="rating_between_one_and_five")),
        migrations.AddConstraint(model_name="rating", constraint=models.CheckConstraint(condition=~Q(reviewer=F("reviewed_user")), name="rating_reviewer_not_reviewed")),
        migrations.AddConstraint(model_name="rating", constraint=models.UniqueConstraint(fields=("job", "reviewer", "reviewed_user"), name="one_rating_per_reviewer_per_job")),
        migrations.AlterField(model_name="report", name="reporter", field=models.ForeignKey(db_column="reporter", on_delete=django.db.models.deletion.RESTRICT, related_name="reports_filed", to=settings.AUTH_USER_MODEL)),
        migrations.AlterField(model_name="report", name="reported_user", field=models.ForeignKey(blank=True, db_column="reported_user", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name="reports_received", to=settings.AUTH_USER_MODEL)),
        migrations.AlterField(model_name="report", name="reported_job", field=models.ForeignKey(blank=True, db_column="reported_job", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name="reports", to="clients.job")),
        migrations.AlterField(model_name="report", name="reason", field=models.CharField(max_length=255)),
        migrations.AlterField(model_name="report", name="status", field=models.CharField(choices=[("OPEN", "Open"), ("UNDER_REVIEW", "Under Review"), ("RESOLVED", "Resolved"), ("DISMISSED", "Dismissed")], default="OPEN", max_length=20)),
        migrations.AddField(model_name="report", name="related_job", field=models.ForeignKey(blank=True, db_column="related_job", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name="related_reports", to="clients.job")),
        migrations.AddField(model_name="report", name="details", field=models.TextField(default="")),
        migrations.AddField(model_name="report", name="admin_action", field=models.TextField(blank=True, default="")),
        migrations.AddField(model_name="report", name="reviewed_by", field=models.ForeignKey(blank=True, db_column="reviewed_by", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_reports", to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name="report", name="created_at", field=models.DateTimeField(auto_now_add=True, null=True)),
        migrations.AddField(model_name="report", name="updated_at", field=models.DateTimeField(auto_now=True, null=True)),
        migrations.AddConstraint(model_name="report", constraint=models.CheckConstraint(condition=Q(reported_user__isnull=False) | Q(reported_job__isnull=False) | Q(related_job__isnull=False), name="report_requires_target")),
        migrations.AddIndex(model_name="report", index=models.Index(fields=["status"], name="reports_status_idx")),
        migrations.RemoveField(model_name="dispute", name="involved_users"),
        migrations.RemoveField(model_name="dispute", name="issue_details"),
        migrations.RemoveField(model_name="dispute", name="resolution_status"),
        migrations.AlterField(model_name="dispute", name="job", field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name="disputes", to="clients.job")),
        migrations.AlterField(model_name="dispute", name="admin_handling", field=models.TextField(blank=True, default="")),
        migrations.AddField(model_name="dispute", name="raised_by", field=models.ForeignKey(db_column="raised_by", on_delete=django.db.models.deletion.RESTRICT, related_name="raised_disputes", to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name="dispute", name="issue", field=models.CharField(max_length=255, default="")),
        migrations.AddField(model_name="dispute", name="details", field=models.TextField(default="")),
        migrations.AddField(model_name="dispute", name="resolution", field=models.TextField(blank=True, default="")),
        migrations.AddField(model_name="dispute", name="status", field=models.CharField(choices=[("OPEN", "Open"), ("UNDER_REVIEW", "Under Review"), ("RESOLVED", "Resolved"), ("DISMISSED", "Dismissed")], default="OPEN", max_length=20)),
        migrations.AddField(model_name="dispute", name="reviewed_by", field=models.ForeignKey(blank=True, db_column="reviewed_by", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_disputes", to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name="dispute", name="created_at", field=models.DateTimeField(auto_now_add=True, null=True)),
        migrations.AddField(model_name="dispute", name="updated_at", field=models.DateTimeField(auto_now=True, null=True)),
        migrations.CreateModel(name="DisputeParticipant", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("dispute", models.ForeignKey(db_column="dispute_id", on_delete=django.db.models.deletion.RESTRICT, to="clients.dispute")),
            ("user", models.ForeignKey(db_column="user_id", on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
        ], options={"db_table": "dispute_users"}),
        migrations.AddField(model_name="dispute", name="involved_users", field=models.ManyToManyField(related_name="disputes", through="clients.DisputeParticipant", to=settings.AUTH_USER_MODEL)),
        migrations.AddConstraint(model_name="disputeparticipant", constraint=models.UniqueConstraint(fields=("dispute", "user"), name="unique_dispute_participant")),
        migrations.AddIndex(model_name="dispute", index=models.Index(fields=["status"], name="disputes_status_idx")),
    ]
