# Generated by Django 5.2.17 on 2026-08-30 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('UPDATE_STUDENT_STATUS', 'Update Student Status'), ('APPROVE_VERIFICATION', 'Approve Verification'), ('REJECT_VERIFICATION', 'Reject Verification'), ('REQUEST_RESUBMISSION', 'Request Resubmission')], max_length=50)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_target_actions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
