# Generated by Django 5.2.17 on 2026-08-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminaction',
            name='action_type',
            field=models.CharField(choices=[('UPDATE_STUDENT_STATUS', 'Update Student Status'), ('UPDATE_CLIENT_STATUS', 'Update Client Status'), ('UPDATE_JOB_STATUS', 'Update Job Status'), ('APPROVE_VERIFICATION', 'Approve Verification'), ('REJECT_VERIFICATION', 'Reject Verification'), ('REQUEST_RESUBMISSION', 'Request Resubmission')], max_length=50),
        ),
    ]
